### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by KlumsyKamikaze** [GitHub-Campus-IITM/support#117]
### Name

Ishaan Jalan

### Smail ID

be20b014@smail.iitm.ac.in

### Additional Context

Hi my name is Ishaan Jalan BE20B014, excited to be here

**Comment by sudip-mondal-2002** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br>Please check your email to get the incitation link<br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. <br> Please join the <a href="https://groups.google.com/a/smail.iitm.ac.in/g/github-campus-group">google group</a> using your smail ID to stay tuned.
