### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Shaadalam9** [GitHub-Campus-IITM/support#118]
### Name

MD SHADAB ALAM

### Smail ID

oe21s007@smail.iitm.ac.in

### Additional Context

.

**Comment by sudip-mondal-2002** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br>Please check your email to get the incitation link<br>Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. <br> Please join the <a href="https://groups.google.com/a/smail.iitm.ac.in/g/github-campus-group">google group</a> using your smail ID to stay tuned.
