### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [GitHub-Campus-IITM/support#365]
### Name

Jyoti prakash Rout

### Smail ID

Btw, I'm not a student of IITM but I am willing to join and be involved in the community.

### Additional Context

I'm an Web Dev enthusiast & a junior pursuing my bachelor in Computer Science & Engineering. I'm interested in Web Devlopment, Machine Learning & DevOps & I enjoy learning new things & stuff as well as I'm a Frontend Devloper with experience building Dynamic & Static Web pages. I am always interested in learning the answers to how, why, and what relates to Technologies around me.

Looking forward to learn, collaborate and grow as a community.

**Comment by sudip-mondal-2002** [comment]
Hey, cool! to see you please mail me ce20b112@smail.iitm.ac.in regarding this.
