### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by cixtor** [GitHub-Campus-IITM/support#518]
### Name

cixtor

### Smail ID

cixtor

### Additional Context

> *What do you like about this community?*

The initiative to bring developers together to collaborate on different projects sounds wonderful.

> *Why do you want to join?*

I have been an active member of the open-source community on GitHub and other platforms, and it is always a joy to find like-minded people willing to share knowledge and experiences. I would love to join thir GitHub organization to help many more developers become excellent open-source maintainers.

**Comment by cixtor** [comment]
@sudip-mondal-2002 it looks like the GitHub Action that handles invitation requests is broken → https://github.com/GitHub-Campus-IITM/support/actions/runs/2794149357 Is there anyone I can do to help you fix it?

**Comment by sudip-mondal-2002** [comment]
You haven't added your smail id, if you're not from IIT Madras please put your Gmail id there
close this and create a new issue

**Comment by cixtor** [comment]
Closing in favor of https://github.com/GitHub-Campus-IITM/support/issues/519
